### ISSUE TITLE
Hello author, I would like to ask you about the problem of model training code

### ISSUE THREAD

**Issue by xiaodongqq** [feixue94/imp-release#3] opened 2023-06-16 09:26 UTC
Hello author, I am glad that you can reply to my previous questions. When I generated the corresponding key points and descriptors according to the readme you provided, I reported the following errors during training under Windows,
![1686907570197](https://github.com/feixue94/imp-release/assets/130161545/c4814633-2b5f-4d18-9ceb-11f9479fb3fb)
![1686907582871](https://github.com/feixue94/imp-release/assets/130161545/d9d94e1c-a5ae-4cd0-a0c6-028b984173e8)

which could not be solved. Could you please tell me how to solve this problem? Thank you very much

**Comment by feixue94** [comment] 2023-06-16 10:20
Hi,
it seems like the input is None. can you print the values of input, e.g., keypoints, scores, and descriptors

**Comment by Uchan1996** [comment] 2023-06-20 04:54
I got this error too.
This error happens at the following code which corresponds the line 104 of the file `trainer.py`.
`data = self.model(pred)`
I printed the input `pred`, and the folloing are shown.

(Pdb) p pred
{'keypoints0': tensor([[[1411.,  662.],
         [1174.,  166.],
         [ 667.,  173.],
         ...,
         [1483.,  772.],
         [ 410.,  690.],
         [1252.,  476.]],

        [[ 423.,  787.],
         [ 297.,  286.],
         [ 436.,  501.],
         ...,
         [  91.,  457.],
         [ 402.,  279.],
         [ 141.,  486.]]], device='cuda:0'), 'keypoints1': tensor([[[1457.,  685.],
         [ 465.,  838.],
         [ 963.,  129.],
         ...,
         [ 783.,  732.],
         [ 321.,  805.],
         [1095.,  290.]],

        [[1088.,  906.],
         [ 764.,  661.],
         [1343., 1147.],
         ...,
         [1066.,  329.],
         [ 645.,  544.],
         [ 720., 1013.]]], device='cuda:0'), 'keypoints0_3d': tensor([[[ 0.4588,  0.1697],
         [ 0.2809, -0.2027],
         [-0.0999, -0.1975],
         ...,
         [ 0.5129,  0.2523],
         [-0.2929,  0.1907],
         [ 0.3394,  0.0300]],

        [[ 0.1841,  0.3737],
         [ 0.0123, -0.3096],
         [ 0.2018, -0.0164],
         ...,
         [-0.2687, -0.0764],
         [ 0.1555, -0.3191],
         [-0.2005, -0.0368]]], device='cuda:0'), 'keypoints1_3d': tensor([[[ 0.4934,  0.1870],
         [-0.2516,  0.3018],
         [ 0.1224, -0.2305],
         ...,
         [-0.0128,  0.2222],
         [-0.3597,  0.2771],
         [ 0.2215, -0.1096]],

        [[ 0.1798,  0.1974],
         [-0.0225,  0.0444],
         [ 0.3391,  0.3479],
         ...,
         [ 0.1661, -0.1630],
         [-0.0968, -0.0287],
         [-0.0500,  0.2642]]], device='cuda:0'), 'norm_keypoints0': tensor([[[ 0.5451,  0.2013],
         [ 0.3335, -0.2415],
         [-0.1192, -0.2353],
         ...,
         [ 0.6094,  0.2996],
         [-0.3487,  0.2263],
         [ 0.4031,  0.0353]],

        [[ 0.1873,  0.3808],
         [ 0.0118, -0.3168],
         [ 0.2054, -0.0174],
         ...,
         [-0.2750, -0.0787],
         [ 0.1580, -0.3265],
         [-0.2054, -0.0383]]], device='cuda:0'), 'norm_keypoints1': tensor([[[ 0.5862,  0.2219],
         [-0.2996,  0.3585],
         [ 0.1451, -0.2746],
         ...,
         [-0.0156,  0.2638],
         [-0.4281,  0.3290],
         [ 0.2629, -0.1308]],

        [[ 0.2567,  0.2817],
         [-0.0326,  0.0629],
         [ 0.4844,  0.4969],
         ...,
         [ 0.2371, -0.2335],
         [-0.1388, -0.0415],
         [-0.0719,  0.3772]]], device='cuda:0'), 'descriptors0': tensor([[[ 0.0238, -0.0567, -0.0032,  ...,  0.0173, -0.0750,  0.0406],
         [ 0.0647,  0.0681, -0.0414,  ..., -0.0398,  0.0879, -0.0400],
         [-0.0396, -0.0289,  0.0631,  ...,  0.1360, -0.0806, -0.0306],
         ...,
         [-0.0550, -0.0663,  0.0950,  ...,  0.0125, -0.0583, -0.0763],
         [ 0.0171, -0.0462, -0.0086,  ...,  0.0602, -0.0127, -0.0107],
         [ 0.0408,  0.0053,  0.0324,  ..., -0.0305,  0.1964,  0.0244]],

        [[-0.0633,  0.0793, -0.0573,  ...,  0.0446, -0.0654, -0.0633],
         [ 0.0030,  0.0801,  0.0382,  ...,  0.0062, -0.0579, -0.0273],
         [-0.0657,  0.0408, -0.0019,  ...,  0.0353, -0.0291, -0.0351],
         ...,
         [-0.0008, -0.0556, -0.0739,  ...,  0.0649,  0.0543, -0.0922],
         [-0.0166, -0.0218, -0.1485,  ...,  0.0586, -0.0360, -0.0789],
         [-0.0809, -0.0636, -0.0546,  ...,  0.0741,  0.0096, -0.0401]]],
       device='cuda:0'), 'descriptors1': tensor([[[ 0.0050, -0.0035,  0.1374,  ...,  0.0094, -0.0281,  0.0678],
         [-0.0893,  0.0055,  0.0633,  ...,  0.0004, -0.0349, -0.0393],
         [ 0.0095, -0.0462, -0.1004,  ..., -0.1320, -0.0263, -0.0443],
         ...,
         [-0.0300,  0.0709,  0.0194,  ...,  0.0050,  0.0326, -0.0620],
         [-0.1291,  0.0873,  0.0028,  ..., -0.0354, -0.0672,  0.0439],
         [ 0.0318,  0.0104, -0.0153,  ..., -0.1591,  0.1163,  0.1220]],

        [[-0.0865, -0.1120, -0.2162,  ...,  0.0252, -0.0594,  0.0194],
         [ 0.0291, -0.0357, -0.0530,  ..., -0.1104,  0.0562, -0.0407],
         [-0.0732, -0.0261, -0.0492,  ...,  0.0175, -0.0460,  0.0762],
         ...,
         [-0.0024, -0.1312,  0.0061,  ...,  0.0476, -0.0699,  0.0155],
         [-0.0371, -0.0231,  0.0029,  ...,  0.0468, -0.0065,  0.0063],
         [-0.0208, -0.0724,  0.0396,  ...,  0.0067, -0.0698, -0.0386]]],
       device='cuda:0'), 'scores0': tensor([[0.0999, 0.0083, 0.1547,  ..., 0.0022, 0.0022, 0.0020],
        [0.0632, 0.2921, 0.4007,  ..., 0.0096, 0.0011, 0.0032]],
       device='cuda:0'), 'scores1': tensor([[0.0037, 0.0125, 0.3313,  ..., 0.0255, 0.2822, 0.0191],
        [0.0258, 0.0270, 0.1008,  ..., 0.2750, 0.0817, 0.0238]],
       device='cuda:0'), 'intrinsics0': tensor([[[1.3316e+03, 0.0000e+00, 8.0000e+02],
         [0.0000e+00, 1.3319e+03, 4.3600e+02],
         [0.0000e+00, 0.0000e+00, 1.0000e+00]],

        [[7.3325e+02, 0.0000e+00, 2.8800e+02],
         [0.0000e+00, 7.3325e+02, 5.1300e+02],
         [0.0000e+00, 0.0000e+00, 1.0000e+00]]], device='cuda:0'), 'intrinsics1': tensor([[[1.3316e+03, 0.0000e+00, 8.0000e+02],
         [0.0000e+00, 1.3319e+03, 4.3600e+02],
         [0.0000e+00, 0.0000e+00, 1.0000e+00]],

        [[1.6015e+03, 0.0000e+00, 8.0000e+02],
         [0.0000e+00, 1.6009e+03, 5.9000e+02],
         [0.0000e+00, 0.0000e+00, 1.0000e+00]]], device='cuda:0'), 'matching_mask': tensor([[[0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         [1., 0., 1.,  ..., 1., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         [0., 1., 1.,  ..., 1., 1., 0.]]], device='cuda:0'), 'gt_pose': tensor([[[-1.7138e-09, -4.9630e-08,  8.0389e-05],
         [ 4.1961e-08, -8.2475e-09,  1.3551e-04],
         [-7.8425e-05, -1.1984e-04, -2.0672e-02]],

        [[ 3.0926e-08, -6.6617e-07,  7.1470e-04],
         [ 5.7669e-07,  8.1411e-08, -4.0416e-04],
         [-1.3865e-03,  8.6950e-04, -1.9811e-01]]], device='cuda:0'), 'P21': tensor([[[ 9.9928e-01, -1.6127e-03,  3.7886e-02, -2.1790e-01],
         [-9.1252e-04,  9.9778e-01,  6.6541e-02,  8.2156e-02],
         [-3.7910e-02, -6.6527e-02,  9.9706e-01,  8.2740e-02],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],

        [[ 9.9785e-01,  6.2298e-02,  2.0433e-02,  3.3242e-01],
         [-6.4771e-02,  9.8499e-01,  1.6000e-01,  7.2909e-01],
         [-1.0159e-02, -1.6098e-01,  9.8691e-01,  6.7503e-01],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]]],
       device='cuda:0'), 'gt_E': tensor([[[-0.0030, -0.0880,  0.0764],
         [ 0.0744, -0.0146,  0.2204],
         [-0.0819, -0.2173, -0.0176]],

        [[ 0.0363, -0.7823,  0.6115],
         [ 0.6770,  0.0956, -0.3143],
         [-0.7491,  0.2820,  0.0383]]], device='cuda:0'), 'file_name': ['5013_00194.jpg_00490.jpg', '0130_15003482359_96878033f8_b.jpg_427977178_c40bd05bcf_o.jpg'], 'image_size0': tensor([[[   3.,  872., 1600.]],

        [[   3., 1026.,  576.]]], device='cuda:0'), 'image_size1': tensor([[[   3.,  872., 1600.]],

        [[   3., 1180., 1600.]]], device='cuda:0'), 'file_name0': ['Undistorted_SfM/5013/images/00194.jpg', 'Undistorted_SfM/0130/images/15003482359_96878033f8_b.jpg'], 'file_name1': ['Undistorted_SfM/5013/images/00490.jpg', 'Undistorted_SfM/0130/images/427977178_c40bd05bcf_o.jpg']}

**Comment by Uchan1996** [comment] 2023-06-20 05:18
I got this error too.
This error happens at the following code, which corresponds to the line 214 of the file `layers.py`.
`message = torch.einsum('bhnm,bdhm->bdhn', prob, value)`
The cause of this error is that the `prob` is `None.`
Could you please fix the code to address this error?

**Comment by Uchan1996** [comment] 2023-06-20 05:38
This error happens at the layer `SharedAttentionalPropagation`.
So, If you train GM instead of DGNNS or AdaGMN, the training works.

**Comment by Uchan1996** [comment] 2023-06-20 06:39
I got the following error, even if I train a GM.
`FileNotFoundError: [Errno 2] No such file or directory: '/data/datasets/object_recognition/sain/MegaDepth_undistorted/training_data/matches_sep_spp/0183/16115.npy'`
I think `dump_megadepth.py` does not generate `16115.npy`.

**Comment by feixue94** [comment] 2023-06-20 15:10
sorry for the late reply. I am a little bit busy these days and will test the code and fix bugs as soon as possible. Thank you very much your patience.

**Comment by feixue94** [comment] 2023-06-21 11:08
I just fixed the bugs in training DGNNS and AdaGMN.

**Comment by feixue94** [comment] 2023-06-21 11:08
> I got the following error, even if I train a GM. `FileNotFoundError: [Errno 2] No such file or directory: '/data/datasets/object_recognition/sain/MegaDepth_undistorted/training_data/matches_sep_spp/0183/16115.npy'` I think `dump_megadepth.py` does not generate `16115.npy`.

you might need to dump the training data first.

**Comment by Uchan1996** [comment] 2023-06-22 01:35
I dumped the training data, which took a few days, and then I ran the `train.py`.

The `assets/mega_scene_nmatches_spp.npy` has the number of valid pairs for each scene.
It says the scene 0183 has 16515 pairs, and the `build_dataset_from_offline` method in `megadepth.py` randomly samples 80 pair ids.
However, the `dump_megadepth.py` generates only 15687 pairs in the folder of `matches_sep_spp/0183`.
I think this is the cause of this error.

Could you please check whether the dumping and training code work correctly from the begining to the end, if you have chance.

**Comment by feixue94** [comment] 2023-06-27 10:06
Dear all,

Sorry for the late reply. The code for dumping data and training model is tested and bugs are fixed now.  The readme file is also updated. Please do a tiny test on 3 scenes for dumping data and training model before using full scenes for training because this could save your time if there is something wrong.

**Comment by feixue94** [comment] 2023-07-17 08:54
I am going to close this. If you have any questions, feel free to reopen it.

**Closed as completed by feixue94** 2023-07-17 08:54 UTC
